/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.hokhau;

import com.toedter.calendar.JDateChooser;
import controller.HoKhauController.ChuyenKhauController;
import java.awt.event.ActionListener;
import javax.swing.JTextField;
import model.HoKhau;
import view.QuanLy;

/**
 *
 * @author nnminh322
 */
public class ChuyenKhau extends javax.swing.JFrame {

    /**
     * Creates new form ChuyenKhau
     */
    public ChuyenKhau() {
        initComponents();
    }

    public ChuyenKhau(QuanLy quanlyView, HoKhau hoKhau) {
        this.quanLy = quanlyView;
        initComponents();
        this.jTextField_SoHoKhau.setText(hoKhau.getSoHoKhau());
        this.chuyenKhauController = new ChuyenKhauController(this);
        ActionListener action = new ChuyenKhauController(this);
        this.jButton_xacNhan.addActionListener(action);
        diaChiCu = hoKhau.getSoNha() + " " + hoKhau.getDuongPho() + ", " + hoKhau.getPhuongXa() + ", " + hoKhau.getQuanHuyen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_SoHoKhau = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_soNha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser_ngayChuyen = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jTextField_duongPho = new javax.swing.JTextField();
        jTextField_xaPhuong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_quanHuyen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_lyDo = new javax.swing.JTextField();
        jButton_xacNhan = new javax.swing.JButton();
        jButton_Huy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Số hộ khẩu");

        jTextField_SoHoKhau.setEditable(false);

        jLabel2.setText("Số nhà");

        jLabel3.setText("Ngày chuyển");

        jLabel4.setText("Đường phố (ấp)");

        jLabel5.setText("Xã phường (Thị trấn)");

        jLabel6.setText("Quận huyện");

        jLabel7.setText("Lý do");

        jTextField_lyDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_lyDoActionPerformed(evt);
            }
        });

        jButton_xacNhan.setText("Xác nhận");
        jButton_xacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_xacNhanActionPerformed(evt);
            }
        });

        jButton_Huy.setText("Huỷ");
        jButton_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1)
                        .addGap(52, 52, 52)
                        .addComponent(jTextField_SoHoKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_soNha)
                            .addComponent(jTextField_duongPho)
                            .addComponent(jTextField_xaPhuong)
                            .addComponent(jTextField_quanHuyen)
                            .addComponent(jDateChooser_ngayChuyen, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(jTextField_lyDo))))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton_xacNhan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Huy)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_SoHoKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_soNha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_duongPho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_xaPhuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_quanHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jDateChooser_ngayChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_lyDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_xacNhan)
                    .addComponent(jButton_Huy))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_lyDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_lyDoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_lyDoActionPerformed

    private void jButton_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HuyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_HuyActionPerformed

    private void jButton_xacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_xacNhanActionPerformed
        // TODO add your handling code here:
        this.quanLy.hienthi();
    }//GEN-LAST:event_jButton_xacNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChuyenKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChuyenKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChuyenKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChuyenKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChuyenKhau().setVisible(true);
            }
        });
    }
    private String diaChiCu;
    public QuanLy quanLy;
    private ChuyenKhauController chuyenKhauController;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Huy;
    private javax.swing.JButton jButton_xacNhan;
    private com.toedter.calendar.JDateChooser jDateChooser_ngayChuyen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField_SoHoKhau;
    private javax.swing.JTextField jTextField_duongPho;
    private javax.swing.JTextField jTextField_lyDo;
    private javax.swing.JTextField jTextField_quanHuyen;
    private javax.swing.JTextField jTextField_soNha;
    private javax.swing.JTextField jTextField_xaPhuong;
    // End of variables declaration//GEN-END:variables

    public JDateChooser getjDateChooser_ngayChuyen() {
        return jDateChooser_ngayChuyen;
    }

    public void setjDateChooser_ngayChuyen(JDateChooser jDateChooser_ngayChuyen) {
        this.jDateChooser_ngayChuyen = jDateChooser_ngayChuyen;
    }

    public JTextField getjTextField_SoHoKhau() {
        return jTextField_SoHoKhau;
    }

    public void setjTextField_SoHoKhau(JTextField jTextField_SoHoKhau) {
        this.jTextField_SoHoKhau = jTextField_SoHoKhau;
    }

    public JTextField getjTextField_duongPho() {
        return jTextField_duongPho;
    }

    public void setjTextField_duongPho(JTextField jTextField_duongPho) {
        this.jTextField_duongPho = jTextField_duongPho;
    }

    public JTextField getjTextField_lyDo() {
        return jTextField_lyDo;
    }

    public void setjTextField_lyDo(JTextField jTextField_lyDo) {
        this.jTextField_lyDo = jTextField_lyDo;
    }

    public JTextField getjTextField_quanHuyen() {
        return jTextField_quanHuyen;
    }

    public void setjTextField_quanHuyen(JTextField jTextField_quanHuyen) {
        this.jTextField_quanHuyen = jTextField_quanHuyen;
    }

    public JTextField getjTextField_soNha() {
        return jTextField_soNha;
    }

    public void setjTextField_soNha(JTextField jTextField_soNha) {
        this.jTextField_soNha = jTextField_soNha;
    }

    public JTextField getjTextField_xaPhuong() {
        return jTextField_xaPhuong;
    }

    public void setjTextField_xaPhuong(JTextField jTextField_xaPhuong) {
        this.jTextField_xaPhuong = jTextField_xaPhuong;
    }

    public String getDiaChiCu() {
        return diaChiCu;
    }

    public void setDiaChiCu(String diaChiCu) {
        this.diaChiCu = diaChiCu;
    }

}
