/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.hokhau;

import controller.HoKhauController.TachKhauController;
import controller.HoKhauController.XemHoKhauController;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.HoKhau;
import model.NhanKhau;
import view.QuanLy;

/**
 *
 * @author nnminh322
 */
public class TachKhau extends javax.swing.JFrame {

    /**
     * Creates new form TachKhau
     */
    public TachKhau() {
        initComponents();
    }

    public TachKhau(QuanLy quanlyView, HoKhau hoKhau) {

        this.quanLy = quanlyView;
        this.tachKhauController = new TachKhauController(this);
        this.hoKhau = hoKhau;
        this.listNhanKhau = this.tachKhauController.hienthiThanhVien(hoKhau);

        initComponents();
        hienthiThanhVien();
        chonChuHo();
        this.jButton_xacNhan.setEnabled(false);
        ActionListener action = new TachKhauController(this);
        this.jButton_kiemTra.addActionListener(action);
        this.jButton_xacNhan.addActionListener(action);
    }

    public void chonChuHo() {
        ArrayList<NhanKhau> listNhanKhauCu = this.listNhanKhau;
        for (NhanKhau nhanKhau : listNhanKhauCu) {
            if (!nhanKhau.getQuanHeVoiChuHo().equals("Chủ hộ")) {
                this.jComboBox_chonChuHo.addItem(nhanKhau.getHoTen());
            }

        }
    }

    public void khoaDuLieu() {
        this.jTextField_soHoKhauMoi.setEditable(false);
        this.jButton_kiemTra.setEnabled(false);
        this.jButton_xacNhan.setEnabled(true);
    }

    public void hienthiThanhVien() {
        ArrayList<NhanKhau> listNhanKhauCuHienThi = this.listNhanKhau;
        DefaultTableModel model = (DefaultTableModel) jTable_chonThanhVien.getModel();
        for (NhanKhau nhanKhau : listNhanKhauCuHienThi) {
            Object[] row = {
                nhanKhau.getHoTen(),
                nhanKhau.getGioiTinh(),
                nhanKhau.getNgaySinh(),
                nhanKhau.getQuanHeVoiChuHo(),};
            model.addRow(row);
        }
    }

    public ArrayList<NhanKhau> thanhVienDuocChon() {
        ArrayList<NhanKhau> listNhanKhauMoi = this.listNhanKhau;
        ArrayList<NhanKhau> listNhanKhauDuocChonMoi = new ArrayList<NhanKhau>();
        int columnIndexOfCheckbox = 4; // the column index of the checkbox column
        for (int i = 0; i < jTable_chonThanhVien.getRowCount(); i++) {
            Boolean isSelected = (Boolean) jTable_chonThanhVien.getValueAt(i, columnIndexOfCheckbox);
            if (isSelected != null && isSelected) {
                listNhanKhauDuocChonMoi.add(listNhanKhauMoi.get(i));

            }
        }
        return listNhanKhauDuocChonMoi;
    }

    public String tenChuHoMoi() {
        return (String) (this.jComboBox_chonChuHo.getSelectedItem());
    }

    public String maHoKhauMoi() {
        return this.jTextField_soHoKhauMoi.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_chonThanhVien = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_chonChuHo = new javax.swing.JComboBox<>();
        jButton_xacNhan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField_soHoKhauMoi = new javax.swing.JTextField();
        jButton_kiemTra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_chonThanhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ và tên", "Giới tính", "Ngày sinh", "Quan hệ với chủ hộ", "Lựa chọn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_chonThanhVien.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(jTable_chonThanhVien);
        jTable_chonThanhVien.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel1.setText("Chủ hộ mới");

        jButton_xacNhan.setText("Xác nhận");
        jButton_xacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_xacNhanActionPerformed(evt);
            }
        });

        jButton2.setText("Huỷ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Số hộ khẩu mới");

        jButton_kiemTra.setText("Kiểm tra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_chonChuHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_soHoKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_kiemTra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jButton_xacNhan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox_chonChuHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_soHoKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_kiemTra))
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_xacNhan)
                            .addComponent(jButton2))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton_xacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_xacNhanActionPerformed
        // TODO add your handling code here:
        this.quanLy.hienthi();
    }//GEN-LAST:event_jButton_xacNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TachKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TachKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TachKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TachKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TachKhau().setVisible(true);
            }
        });
    }
    public QuanLy quanLy;
    private HoKhau hoKhau;
    private TachKhauController tachKhauController;
    private ArrayList<NhanKhau> listNhanKhau;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_kiemTra;
    private javax.swing.JButton jButton_xacNhan;
    private javax.swing.JComboBox<String> jComboBox_chonChuHo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_chonThanhVien;
    private javax.swing.JTextField jTextField_soHoKhauMoi;
    // End of variables declaration//GEN-END:variables

    public JButton getjButton_kiemTra() {
        return jButton_kiemTra;
    }

    public void setjButton_kiemTra(JButton jButton_kiemTra) {
        this.jButton_kiemTra = jButton_kiemTra;
    }

    public JTextField getjTextField_soHoKhauMoi() {
        return jTextField_soHoKhauMoi;
    }

    public void setjTextField_soHoKhauMoi(JTextField jTextField_soHoKhauMoi) {
        this.jTextField_soHoKhauMoi = jTextField_soHoKhauMoi;
    }

    public JButton getjButton_xacNhan() {
        return jButton_xacNhan;
    }

    public void setjButton_xacNhan(JButton jButton_xacNhan) {
        this.jButton_xacNhan = jButton_xacNhan;
    }

    public HoKhau getHoKhau() {
        return hoKhau;
    }

    public void setHoKhau(HoKhau hoKhau) {
        this.hoKhau = hoKhau;
    }

}
