/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.hokhau;

import controller.HoKhauController.ThemHoKhauController;
import java.awt.event.ActionListener;
import javax.swing.JTextField;
import model.NhanKhau;
import view.QuanLy;

/**
 *
 * @author nnminh322
 */
public class ThemHoKhau extends javax.swing.JFrame {

    /**
     * Creates new form ChuyenKhau
     */
    public ThemHoKhau() {
        initComponents();
    }

    public ThemHoKhau(QuanLy quanly, NhanKhau chuHo) {
        this.quanLy = quanly;
        initComponents();
        this.jTextField_chuHo.setText(chuHo.getHoTen());
        this.jTextField_maHoKhau.setText(chuHo.getSoHoKhau());
        this.jTextField_chuHo.setEditable(false);
        this.jTextField_maHoKhau.setEditable(false);
        this.themHoKhauController = new ThemHoKhauController(this);
        ActionListener action = new ThemHoKhauController(this);
        this.jButton_xacNhan.addActionListener(action);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_maHoKhau = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_soNha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_duongPho = new javax.swing.JTextField();
        jTextField_phuongXa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_quanHuyen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_chuHo = new javax.swing.JTextField();
        jButton_xacNhan = new javax.swing.JButton();
        jButton_huy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã hộ khẩu");

        jTextField_maHoKhau.setEditable(false);

        jLabel2.setText("Số nhà");

        jLabel4.setText("Đường phố (ấp)");

        jLabel5.setText("Xã phường (Thị trấn)");

        jLabel6.setText("Quận huyện");

        jLabel7.setText("Chủ hộ");

        jTextField_chuHo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_chuHoActionPerformed(evt);
            }
        });

        jButton_xacNhan.setText("Xác nhận");
        jButton_xacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_xacNhanActionPerformed(evt);
            }
        });

        jButton_huy.setText("Huỷ");
        jButton_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_huyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1)
                        .addGap(52, 52, 52)
                        .addComponent(jTextField_maHoKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_soNha, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(jTextField_duongPho)
                            .addComponent(jTextField_phuongXa)
                            .addComponent(jTextField_quanHuyen)
                            .addComponent(jTextField_chuHo))))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton_xacNhan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_huy)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_maHoKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_soNha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_chuHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_duongPho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_phuongXa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_quanHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_xacNhan)
                    .addComponent(jButton_huy))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_chuHoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_chuHoActionPerformed
        // TODO add your handling code here:
        this.quanLy.hienthi();
    }//GEN-LAST:event_jTextField_chuHoActionPerformed

    private void jButton_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_huyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_huyActionPerformed

    private void jButton_xacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_xacNhanActionPerformed
        // TODO add your handling code here:
        this.quanLy.hienthi();
    }//GEN-LAST:event_jButton_xacNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemHoKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemHoKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemHoKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemHoKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemHoKhau().setVisible(true);
            }
        });
    }
    public QuanLy quanLy;
    private ThemHoKhauController themHoKhauController;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_huy;
    private javax.swing.JButton jButton_xacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField_chuHo;
    private javax.swing.JTextField jTextField_duongPho;
    private javax.swing.JTextField jTextField_maHoKhau;
    private javax.swing.JTextField jTextField_phuongXa;
    private javax.swing.JTextField jTextField_quanHuyen;
    private javax.swing.JTextField jTextField_soNha;
    // End of variables declaration//GEN-END:variables

    public JTextField getjTextField_chuHo() {
        return jTextField_chuHo;
    }

    public void setjTextField_chuHo(JTextField jTextField_chuHo) {
        this.jTextField_chuHo = jTextField_chuHo;
    }

    public JTextField getjTextField_duongPho() {
        return jTextField_duongPho;
    }

    public void setjTextField_duongPho(JTextField jTextField_duongPho) {
        this.jTextField_duongPho = jTextField_duongPho;
    }

    public JTextField getjTextField_maHoKhau() {
        return jTextField_maHoKhau;
    }

    public void setjTextField_maHoKhau(JTextField jTextField_maHoKhau) {
        this.jTextField_maHoKhau = jTextField_maHoKhau;
    }

    public JTextField getjTextField_phuongXa() {
        return jTextField_phuongXa;
    }

    public void setjTextField_phuongXa(JTextField jTextField_phuongXa) {
        this.jTextField_phuongXa = jTextField_phuongXa;
    }

    public JTextField getjTextField_quanHuyen() {
        return jTextField_quanHuyen;
    }

    public void setjTextField_quanHuyen(JTextField jTextField_quanHuyen) {
        this.jTextField_quanHuyen = jTextField_quanHuyen;
    }

    public JTextField getjTextField_soNha() {
        return jTextField_soNha;
    }

    public void setjTextField_soNha(JTextField jTextField_soNha) {
        this.jTextField_soNha = jTextField_soNha;
    }

}
