/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.hokhau;

import controller.HoKhauController.XemHoKhauController;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.HoKhau;
import model.NhanKhau;
import model.ThayDoiHoKhau;
import view.QuanLy;

/**
 *
 * @author nnminh322
 */
public class XemHoKhau extends javax.swing.JFrame {

    /**
     * Creates new form XemHoKhau
     */
    public XemHoKhau() {
        initComponents();
    }

    public XemHoKhau(QuanLy quanlyView, HoKhau hoKhau) {
        this.xemHoKhauController = new XemHoKhauController(this);
        this.hoKhau = hoKhau;
        initComponents();
        hienthiThanhVien();
        hienthiThayDoi();
    }

    public void hienthiThanhVien() {
        ArrayList<NhanKhau> listNhanKhau = this.xemHoKhauController.hienthiThanhVien(hoKhau);
        DefaultTableModel model = (DefaultTableModel) jTable_ThongTinThanhVien.getModel();
        model.setRowCount(0);
        for (NhanKhau nhanKhau : listNhanKhau) {
            Object[] row = {
                nhanKhau.getHoTen(),
                nhanKhau.getNgaySinh(),
                nhanKhau.getGioiTinh(),
                nhanKhau.getNgheNghiep(),
                nhanKhau.getCCCD(),
                nhanKhau.getQuanHeVoiChuHo(),};
            model.addRow(row);
        }
    }

    public void hienthiThayDoi() {
        ArrayList<ThayDoiHoKhau> listThayDoiHoKhau = this.xemHoKhauController.hienthiThayDoi(hoKhau);
        DefaultTableModel model = (DefaultTableModel) jTable_LichSuThayDoi.getModel();
        model.setRowCount(0);
        for (ThayDoiHoKhau thayDoiHoKhau : listThayDoiHoKhau) {
            Object[] row = {
                thayDoiHoKhau.getNgayThayDoi(),
                thayDoiHoKhau.getLyDo(),};
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ThongTinThanhVien = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_LichSuThayDoi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable_ThongTinThanhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ và tên", "Ngày sinh", "Giới tính", "Nghệ nghiệp", "Căn cước công dân", "Quan hệ với chủ hộ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_ThongTinThanhVien);

        jTable_LichSuThayDoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ngày thay đổi", "Lý do thay đổi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_LichSuThayDoi);
        if (jTable_LichSuThayDoi.getColumnModel().getColumnCount() > 0) {
            jTable_LichSuThayDoi.getColumnModel().getColumn(0).setResizable(false);
            jTable_LichSuThayDoi.getColumnModel().getColumn(0).setPreferredWidth(-5);
            jTable_LichSuThayDoi.getColumnModel().getColumn(1).setMinWidth(500);
        }

        jLabel1.setText("Thông tin thành viên");

        jLabel2.setText("Lịch sử thay đổi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XemHoKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XemHoKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XemHoKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XemHoKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XemHoKhau().setVisible(true);
            }
        });
    }
    public XemHoKhauController xemHoKhauController;
    private HoKhau hoKhau;
    private ThayDoiHoKhau thayDoiHoKhau;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_LichSuThayDoi;
    private javax.swing.JTable jTable_ThongTinThanhVien;
    // End of variables declaration//GEN-END:variables
}
