/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.nhankhau;

import com.toedter.calendar.JDateChooser;
import controller.NhanKhauController.DKTamTruController;
import java.awt.event.ActionListener;
import javax.swing.JTextField;
import view.QuanLy;

/**
 *
 * @author nnminh322
 */
public class DKTamTru extends javax.swing.JFrame {

    /**
     * Creates new form ThayDoiNhanKhau
     */
    public DKTamTru(QuanLy quanLy) {
        this.quanLy = quanLy;
        initComponents();
        this.dKTamTruController = new DKTamTruController(this);
        ActionListener action = new DKTamTruController(this);
        this.jButton_kiemTra.addActionListener(action);
        this.jButton_xacNhan.addActionListener(action);
        khoa();
    }

    public void khoa() {
        this.jTextField_maGiayTamTru.setEditable(false);
        this.jTextField_noiTamTru.setEditable(false);
        this.jTextField_lyDo.setEditable(false);
        this.jDateChooser_tuNgay.setEnabled(false);
        this.jDateChooser_denNgay.setEnabled(false);
    }

    public void mo() {
        this.jTextField_CCCD.setEditable(false);
        this.jButton_kiemTra.setEnabled(false);
        this.jTextField_maGiayTamTru.setEditable(true);
        this.jTextField_noiTamTru.setEditable(true);
        this.jTextField_lyDo.setEditable(true);
        this.jDateChooser_tuNgay.setEnabled(true);
        this.jDateChooser_denNgay.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField_noiTamTru = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_lyDo = new javax.swing.JTextField();
        jButton_xacNhan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField_maGiayTamTru = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser_tuNgay = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser_denNgay = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jTextField_CCCD = new javax.swing.JTextField();
        jButton_kiemTra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("Nơi tạm trú");

        jLabel4.setText("Lý do");

        jButton_xacNhan.setText("Xác nhận");
        jButton_xacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_xacNhanActionPerformed(evt);
            }
        });

        jButton2.setText("Huỷ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Mã giấy tạm trú");

        jLabel6.setText("Từ ngày");

        jLabel7.setText("Đến ngày");

        jLabel1.setText("CCCD");

        jButton_kiemTra.setText("Kiểm tra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_xacNhan)
                .addGap(64, 64, 64)
                .addComponent(jButton2)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_lyDo)
                    .addComponent(jDateChooser_tuNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addComponent(jDateChooser_denNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_noiTamTru, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_CCCD, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_kiemTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextField_maGiayTamTru))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_kiemTra))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_maGiayTamTru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_noiTamTru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_lyDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel6))
                    .addComponent(jDateChooser_tuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jDateChooser_denNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_xacNhan)
                    .addComponent(jButton2))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton_xacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_xacNhanActionPerformed
        // TODO add your handling code here:
        this.quanLy.hienthi();

    }//GEN-LAST:event_jButton_xacNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DKTamTru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DKTamTru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DKTamTru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DKTamTru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new DKTamTru().setVisible(true);
            }
        });
    }
    public QuanLy quanLy;
    private DKTamTruController dKTamTruController;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_kiemTra;
    private javax.swing.JButton jButton_xacNhan;
    private com.toedter.calendar.JDateChooser jDateChooser_denNgay;
    private com.toedter.calendar.JDateChooser jDateChooser_tuNgay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField_CCCD;
    private javax.swing.JTextField jTextField_lyDo;
    private javax.swing.JTextField jTextField_maGiayTamTru;
    private javax.swing.JTextField jTextField_noiTamTru;
    // End of variables declaration//GEN-END:variables

    public JDateChooser getjDateChooser_tuNgay() {
        return jDateChooser_tuNgay;
    }

    public void setjDateChooser_tuNgay(JDateChooser jDateChooser_tuNgay) {
        this.jDateChooser_tuNgay = jDateChooser_tuNgay;
    }

    public JTextField getjTextField_CCCD() {
        return jTextField_CCCD;
    }

    public void setjTextField_CCCD(JTextField jTextField_CCCD) {
        this.jTextField_CCCD = jTextField_CCCD;
    }

    public JTextField getjTextField_lyDo() {
        return jTextField_lyDo;
    }

    public void setjTextField_lyDo(JTextField jTextField_lyDo) {
        this.jTextField_lyDo = jTextField_lyDo;
    }

    public JTextField getjTextField_maGiayTamTru() {
        return jTextField_maGiayTamTru;
    }

    public void setjTextField_maGiayTamTru(JTextField jTextField_maGiayTamTru) {
        this.jTextField_maGiayTamTru = jTextField_maGiayTamTru;
    }

    public JTextField getjTextField_noiTamTru() {
        return jTextField_noiTamTru;
    }

    public void setjTextField_noiTamTru(JTextField jTextField_noiTamTru) {
        this.jTextField_noiTamTru = jTextField_noiTamTru;
    }

    public JDateChooser getjDateChooser_denNgay() {
        return jDateChooser_denNgay;
    }

    public void setjDateChooser_denNgay(JDateChooser jDateChooser_denNgay) {
        this.jDateChooser_denNgay = jDateChooser_denNgay;
    }

}
