/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.nhankhau;

import com.toedter.calendar.JDateChooser;
import controller.NhanKhauController.KhaiTuController;
import java.awt.event.ActionListener;
import javax.swing.JTextField;
import model.NhanKhau;
import view.QuanLy;

/**
 *
 * @author nnminh322
 */
public class KhaiTu extends javax.swing.JFrame {

    /**
     * Creates new form LichSuThayDoi
     */
    public KhaiTu() {
        initComponents();
    }

    public KhaiTu(QuanLy quanLy, NhanKhau nhanKhau) {
        initComponents();
        this.quanLy = quanLy;
        this.nhanKhau = nhanKhau;
        hienthi();
        init();
    }

    public void hienthi() {
        this.jTextField_hoTen.setText(nhanKhau.getHoTen());
        this.jTextField_maHoKhau.setText(nhanKhau.getSoHoKhau());
        this.jTextField_gioiTinh.setText(nhanKhau.getGioiTinh());
        this.jTextField_CCCD.setText(nhanKhau.getCCCD());
        this.jTextField_ngaySinh.setText(nhanKhau.getNgaySinh().toString());
    }

    public void init() {
        this.khaiTuController = new KhaiTuController(this);
        ActionListener action = new KhaiTuController(this);
        this.jButton_khaiTu.addActionListener(action);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_hoTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_maHoKhau = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_ngaySinh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_gioiTinh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_CCCD = new javax.swing.JTextField();
        jButton_khaiTu = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_lyDo = new javax.swing.JTextField();
        jDateChooser_ngayMat = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Họ và tên");

        jTextField_hoTen.setEditable(false);

        jLabel2.setText("Mã hộ khẩu");

        jTextField_maHoKhau.setEditable(false);

        jLabel3.setText("Ngày sinh");

        jTextField_ngaySinh.setEditable(false);

        jLabel4.setText("Giới tính");

        jTextField_gioiTinh.setEditable(false);

        jLabel5.setText("CCCD");

        jTextField_CCCD.setEditable(false);

        jButton_khaiTu.setText("Khai tử");
        jButton_khaiTu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_khaiTuActionPerformed(evt);
            }
        });

        jButton2.setText("Huỷ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Ngày mất");

        jLabel8.setText("Lý do mất");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 146, Short.MAX_VALUE)
                        .addComponent(jButton_khaiTu)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_hoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(jTextField_maHoKhau)
                            .addComponent(jTextField_ngaySinh)
                            .addComponent(jTextField_gioiTinh)
                            .addComponent(jTextField_CCCD)
                            .addComponent(jTextField_lyDo)
                            .addComponent(jDateChooser_ngayMat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_maHoKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_gioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jDateChooser_ngayMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_lyDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton_khaiTu))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton_khaiTuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_khaiTuActionPerformed
        // TODO add your handling code here:
        this.quanLy.hienthi();
    }//GEN-LAST:event_jButton_khaiTuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhaiTu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhaiTu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhaiTu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhaiTu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhaiTu().setVisible(true);
            }
        });
    }
    private NhanKhau nhanKhau;
    private KhaiTuController khaiTuController;
    public QuanLy quanLy;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_khaiTu;
    private com.toedter.calendar.JDateChooser jDateChooser_ngayMat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField_CCCD;
    private javax.swing.JTextField jTextField_gioiTinh;
    private javax.swing.JTextField jTextField_hoTen;
    private javax.swing.JTextField jTextField_lyDo;
    private javax.swing.JTextField jTextField_maHoKhau;
    private javax.swing.JTextField jTextField_ngaySinh;
    // End of variables declaration//GEN-END:variables

    public NhanKhau getNhanKhau() {
        return nhanKhau;
    }

    public void setNhanKhau(NhanKhau nhanKhau) {
        this.nhanKhau = nhanKhau;
    }

    public JDateChooser getjDateChooser_ngayMat() {
        return jDateChooser_ngayMat;
    }

    public void setjDateChooser_ngayMat(JDateChooser jDateChooser_ngayMat) {
        this.jDateChooser_ngayMat = jDateChooser_ngayMat;
    }

    public JTextField getjTextField_lyDo() {
        return jTextField_lyDo;
    }

    public void setjTextField_lyDo(JTextField jTextField_lyDo) {
        this.jTextField_lyDo = jTextField_lyDo;
    }

}
