/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.QuanLyController;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.HoKhau;
import model.NhanKhau;
import model.TamTru;
import model.TamVang;

/**
 *
 * @author sv_minhnn
 */
public class QuanLy extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public QuanLy() {
        initComponents();
        this.setVisible(true);
        init();
        hienthi();
    }

    public void init() {
        this.quanLyController = new QuanLyController(this);
        ActionListener action = new QuanLyController(this);
        this.jButton_ChuyenHoKhau.addActionListener(action);
        this.jButton_DangKyTamTru.addActionListener(action);
        this.jButton_DangKyTamVang.addActionListener(action);
        this.jButton_KhaiTuNhanKhau.addActionListener(action);
        this.jButton_TachKhau.addActionListener(action);
        this.jButton_khaiSinh.addActionListener(action);
        this.jButton_ThemHoKhau.addActionListener(action);
        this.jButton_ThemNhanKhau.addActionListener(action);
        this.jButton_ThongKe.addActionListener(action);
        this.jButton_TimKiemHoKhau.addActionListener(action);
        this.jButton_TimKiemNhanKhau.addActionListener(action);
        this.jButton_XemNhanKhau.addActionListener(action);
        this.jButton_XemThanhVien.addActionListener(action);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton_TachKhau = new javax.swing.JButton();
        jButton_ThemHoKhau = new javax.swing.JButton();
        jButton_ChuyenHoKhau = new javax.swing.JButton();
        jButton_XemThanhVien = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_HoKhau = new javax.swing.JTable();
        jButton_TimKiemHoKhau = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jTextField_TuKhoaHoKhau = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton_DangKyTamVang = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_NhanKhau = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton_TimKiemNhanKhau = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField_TuKhoaNhanKhau = new javax.swing.JTextField();
        jButton_KhaiTuNhanKhau = new javax.swing.JButton();
        jButton_khaiSinh = new javax.swing.JButton();
        jButton_XemNhanKhau = new javax.swing.JButton();
        jButton_DangKyTamTru = new javax.swing.JButton();
        jButton_ThemNhanKhau = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_GioiTinh = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_TinhTrang = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_TuNam = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_DenNam = new javax.swing.JTextField();
        jButton_ThongKe = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_TuDoTuoi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_DenDoTuoi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_KetQuaThongKe = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jTextField_SoLuongThongKe = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable_DanhSachTamTru = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable_DanhSachTamVang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setLocation(new java.awt.Point(500, 500));
        jTabbedPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentMoved(evt);
            }
        });

        jButton_TachKhau.setText("Tách khẩu");

        jButton_ThemHoKhau.setText("Thêm hộ khẩu");

        jButton_ChuyenHoKhau.setText("Chuyển đi");

        jButton_XemThanhVien.setText("Xem thành viên");
        jButton_XemThanhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_XemThanhVienMouseClicked(evt);
            }
        });
        jButton_XemThanhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XemThanhVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_TachKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_ThemHoKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_ChuyenHoKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_XemThanhVien, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jButton_XemThanhVien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_ChuyenHoKhau)
                .addGap(12, 12, 12)
                .addComponent(jButton_TachKhau)
                .addGap(14, 14, 14)
                .addComponent(jButton_ThemHoKhau)
                .addGap(41, 41, 41))
        );

        jTable_HoKhau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số hộ khẩu", "Chủ hộ", "Số nhà", "Đường phố (ấp)", "Phường (xã, thị trấn)", "Quận (huyện)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_HoKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_HoKhauMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_HoKhau);

        jScrollPane3.setViewportView(jScrollPane1);

        jButton_TimKiemHoKhau.setText("Tìm kiếm");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Số hộ khẩu", "Chủ hộ" }));

        jLabel15.setText("Tìm kiếm theo:");

        jLabel13.setText("Từ khoá");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel13)
                        .addGap(26, 26, 26)
                        .addComponent(jTextField_TuKhoaHoKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_TimKiemHoKhau)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_TimKiemHoKhau)
                    .addComponent(jTextField_TuKhoaHoKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hộ khẩu", jPanel2);

        jButton_DangKyTamVang.setText("ĐK Tạm vắng");

        jTable_NhanKhau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ và tên", "Bí danh", "Ngày sinh", "Nguyên quán", "Dân tộc", "Nghề nghiệp", "Căn cước", "Giới tính", "Số hộ khẩu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_NhanKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_NhanKhauMouseClicked(evt);
            }
        });
        jTable_NhanKhau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable_NhanKhauKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_NhanKhau);

        jScrollPane10.setViewportView(jScrollPane2);

        jLabel14.setText("Từ khoá");

        jLabel16.setText("Tìm kiếm theo:");

        jButton_TimKiemNhanKhau.setText("Tìm kiếm");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Họ và tên", "CCCD" }));

        jButton_KhaiTuNhanKhau.setText("Khai tử");

        jButton_khaiSinh.setText("Khai sinh");

        jButton_XemNhanKhau.setText("Xem thông tin");
        jButton_XemNhanKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_XemNhanKhauMouseClicked(evt);
            }
        });
        jButton_XemNhanKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XemNhanKhauActionPerformed(evt);
            }
        });

        jButton_DangKyTamTru.setText("ĐK Tạm trú");

        jButton_ThemNhanKhau.setText("Thêm nhân khẩu");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton_KhaiTuNhanKhau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_DangKyTamVang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(jButton_khaiSinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_DangKyTamTru, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 163, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_XemNhanKhau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_ThemNhanKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
                        .addGap(18, 18, 18))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jTextField_TuKhoaNhanKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_TimKiemNhanKhau)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField_TuKhoaNhanKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_TimKiemNhanKhau)
                    .addComponent(jLabel16))
                .addGap(18, 21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton_XemNhanKhau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_ThemNhanKhau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_DangKyTamTru, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_DangKyTamVang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_KhaiTuNhanKhau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_khaiSinh)))
                .addGap(48, 48, 48))
        );

        jTabbedPane1.addTab("Nhân khẩu", jPanel3);

        jLabel1.setText("Giới tính");

        jComboBox_GioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toàn bộ", "Nam", "Nữ" }));

        jLabel2.setText("Tình trạng");

        jComboBox_TinhTrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toàn bộ", "Tạm trú", "Tạm vắng" }));

        jLabel3.setText("Năm");

        jLabel4.setText("từ");

        jLabel5.setText("đến");

        jButton_ThongKe.setText("Thống kê");

        jLabel6.setText("Độ tuổi");

        jLabel7.setText("từ");

        jLabel8.setText("đến");

        jLabel9.setText("Kết quả");

        jTable_KetQuaThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ và tên", "Ngày sinh", "Giới tính", "Tình trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable_KetQuaThongKe);

        jScrollPane5.setViewportView(jScrollPane4);

        jLabel10.setText("Số lượng:");

        jTextField_SoLuongThongKe.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_SoLuongThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_TuDoTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_DenDoTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(212, 212, 212)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(27, 27, 27))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jComboBox_TinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)
                                .addComponent(jButton_ThongKe))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextField_TuNam, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_DenNam, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(334, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox_TinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_ThongKe)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_TuNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_DenNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jTextField_TuDoTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_DenDoTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(75, 75, 75)
                .addComponent(jLabel9)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_SoLuongThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thống kê", jPanel4);

        jLabel11.setText("Danh sách giấy tạm trú");

        jLabel12.setText("Danh sách giấy tạm vắng");

        jTable_DanhSachTamTru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tạm trú", "CCCD", "Nơi tạm trú", "Lý do tạm trú", "Từ ngày", "Đến ngày"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable_DanhSachTamTru);

        jScrollPane8.setViewportView(jScrollPane6);

        jTable_DanhSachTamVang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tạm vắng", "CCCD", "SĐT", "Lý do", "Từ ngày", "Đến ngày"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable_DanhSachTamVang);

        jScrollPane9.setViewportView(jScrollPane7);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tạm trú và tạm vắng", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1ComponentMoved

    private void jTable_NhanKhauKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable_NhanKhauKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_NhanKhauKeyReleased

    private void jTable_NhanKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_NhanKhauMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_NhanKhauMouseClicked

    private void jTable_HoKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_HoKhauMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_HoKhauMouseClicked

//    public void showDetailCitizen(){
//        int i = jTable2.getSelectedRow();
//        
//    }

    private void jButton_XemThanhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XemThanhVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_XemThanhVienActionPerformed

    private void jButton_XemThanhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_XemThanhVienMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_XemThanhVienMouseClicked

    private void jButton_XemNhanKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XemNhanKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_XemNhanKhauActionPerformed

    private void jButton_XemNhanKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_XemNhanKhauMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_XemNhanKhauMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLy().setVisible(true);
            }
        });
    }

    public void hienthi() {
        hienthiNhanKhau();
        hienthiHoKhau();
        hienthiTamTru();
        hienthiTamVang();
    }

    public void hienthiNhanKhau() {
        ArrayList<NhanKhau> listNhanKhau = this.quanLyController.hienthiNhanKhau();
        DefaultTableModel model = (DefaultTableModel) jTable_NhanKhau.getModel();
        model.setRowCount(0);
        for (NhanKhau nhanKhau : listNhanKhau) {
            Object[] row = {
                nhanKhau.getHoTen(),
                nhanKhau.getBiDanh(),
                nhanKhau.getNgaySinh(),
                nhanKhau.getNguyenQuan(),
                nhanKhau.getDanToc(),
                nhanKhau.getNgheNghiep(),
                nhanKhau.getCCCD(),
                nhanKhau.getGioiTinh(),
                nhanKhau.getSoHoKhau(),};
            model.addRow(row);
        }
    }

    public void hienthiHoKhau() {
        ArrayList<HoKhau> listHoKhau = this.quanLyController.hienthiHoKhau();
        DefaultTableModel model = (DefaultTableModel) jTable_HoKhau.getModel();
        model.setRowCount(0);
        for (HoKhau hoKhau : listHoKhau) {
            Object[] row = {
                hoKhau.getSoHoKhau(),
                hoKhau.getHoTenChuHo(),
                hoKhau.getSoNha(),
                hoKhau.getDuongPho(),
                hoKhau.getPhuongXa(),
                hoKhau.getQuanHuyen(),};
            model.addRow(row);
        }
    }

    public void hienthiTamTru() {
        ArrayList<TamTru> listTamTru = this.quanLyController.hienthiTamTru();
        DefaultTableModel model = (DefaultTableModel) jTable_DanhSachTamTru.getModel();
        model.setRowCount(0);
        for (TamTru tamTru : listTamTru) {
            Object[] row = {
                tamTru.getMaGiay(),
                tamTru.getCCCD(),
                tamTru.getNoiTamTru(),
                tamTru.getLyDo(),
                tamTru.getTuNgay(),
                tamTru.getDenNgay(),};
            model.addRow(row);
        }
    }

    public void hienthiTamVang() {
        ArrayList<TamVang> listTamVang = this.quanLyController.hienthiTamVang();
        DefaultTableModel model = (DefaultTableModel) jTable_DanhSachTamVang.getModel();
        model.setRowCount(0);
        for (TamVang tamVang : listTamVang) {
            Object[] row = {
                tamVang.getMaGiay(),
                tamVang.getCCCD(),
                tamVang.getSDT(),
                tamVang.getLyDo(),
                tamVang.getTuNgay(),
                tamVang.getDenNgay(),};
            model.addRow(row);
        }
    }
    private QuanLyController quanLyController;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ChuyenHoKhau;
    private javax.swing.JButton jButton_DangKyTamTru;
    private javax.swing.JButton jButton_DangKyTamVang;
    private javax.swing.JButton jButton_KhaiTuNhanKhau;
    private javax.swing.JButton jButton_TachKhau;
    private javax.swing.JButton jButton_ThemHoKhau;
    private javax.swing.JButton jButton_ThemNhanKhau;
    private javax.swing.JButton jButton_ThongKe;
    private javax.swing.JButton jButton_TimKiemHoKhau;
    private javax.swing.JButton jButton_TimKiemNhanKhau;
    private javax.swing.JButton jButton_XemNhanKhau;
    private javax.swing.JButton jButton_XemThanhVien;
    private javax.swing.JButton jButton_khaiSinh;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox_GioiTinh;
    private javax.swing.JComboBox<String> jComboBox_TinhTrang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_DanhSachTamTru;
    private javax.swing.JTable jTable_DanhSachTamVang;
    private javax.swing.JTable jTable_HoKhau;
    private javax.swing.JTable jTable_KetQuaThongKe;
    private javax.swing.JTable jTable_NhanKhau;
    private javax.swing.JTextField jTextField_DenDoTuoi;
    private javax.swing.JTextField jTextField_DenNam;
    private javax.swing.JTextField jTextField_SoLuongThongKe;
    private javax.swing.JTextField jTextField_TuDoTuoi;
    private javax.swing.JTextField jTextField_TuKhoaHoKhau;
    private javax.swing.JTextField jTextField_TuKhoaNhanKhau;
    private javax.swing.JTextField jTextField_TuNam;
    // End of variables declaration//GEN-END:variables

    public JTable getjTable1() {
        return jTable_HoKhau;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable_HoKhau = jTable1;
    }

    public JTable getjTable2() {
        return jTable_NhanKhau;
    }

    public void setjTable2(JTable jTable2) {
        this.jTable_NhanKhau = jTable2;
    }

    public JTable getjTable_DanhSachTamTru() {
        return jTable_DanhSachTamTru;
    }

    public void setjTable_DanhSachTamTru(JTable jTable_DanhSachTamTru) {
        this.jTable_DanhSachTamTru = jTable_DanhSachTamTru;
    }

    public JTable getjTable_DanhSachTamVang() {
        return jTable_DanhSachTamVang;
    }

    public void setjTable_DanhSachTamVang(JTable jTable_DanhSachTamVang) {
        this.jTable_DanhSachTamVang = jTable_DanhSachTamVang;
    }

    public JTable getjTable_HoKhau() {
        return jTable_HoKhau;
    }

    public void setjTable_HoKhau(JTable jTable_HoKhau) {
        this.jTable_HoKhau = jTable_HoKhau;
    }

    public JTable getjTable_KetQuaThongKe() {
        return jTable_KetQuaThongKe;
    }

    public void setjTable_KetQuaThongKe(JTable jTable_KetQuaThongKe) {
        this.jTable_KetQuaThongKe = jTable_KetQuaThongKe;
    }

    public JTable getjTable_NhanKhau() {
        return jTable_NhanKhau;
    }

    public void setjTable_NhanKhau(JTable jTable_NhanKhau) {
        this.jTable_NhanKhau = jTable_NhanKhau;
    }

    public HoKhau getHoKhau(int selected) {

        String soHoKhau = this.jTable_HoKhau.getValueAt(selected, 0).toString();
        String hoTenChuHo = this.jTable_HoKhau.getValueAt(selected, 1).toString();
        int soNha = Integer.parseInt(this.jTable_HoKhau.getValueAt(selected, 2).toString());
        String duongPho = this.jTable_HoKhau.getValueAt(selected, 3).toString();
        String phuongXa = this.jTable_HoKhau.getValueAt(selected, 4).toString();
        String quanHuyen = this.jTable_HoKhau.getValueAt(selected, 5).toString();

        return new HoKhau(soHoKhau, hoTenChuHo, soNha, duongPho, phuongXa, quanHuyen);
    }

}
