/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.sinhhoat;

import controller.HoKhauController.ThemHoKhauController;
import controller.QuanLySinhHoat.GhiNhanThamGiaController;
import java.awt.event.ActionListener;
import javax.swing.JTextField;
import model.NhanKhau;
import view.QuanLy;
import view.QuanLySinhHoat;

/**
 *
 * @author nnminh322
 */
public class GhiNhanThamGia extends javax.swing.JFrame {

    /**
     * Creates new form ChuyenKhau
     */
    public GhiNhanThamGia() {
        initComponents();
    }
    
    public GhiNhanThamGia(QuanLySinhHoat quanLySinhHoat, String maCuocHop) {
        this.quanLySinhHoat = quanLySinhHoat;
        initComponents();
        this.jTextField_maCuocHop.setText(maCuocHop);
        this.jTextField_maCuocHop.setEditable(false);
        this.ghiNhanThamGiaController = new GhiNhanThamGiaController(this);
        ActionListener action = new GhiNhanThamGiaController(this);
        this.jButton_kiemTra.addActionListener(action);
        this.jButton_xacNhan.addActionListener(action);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_maHoKhau = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_maCuocHop = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_chuHo = new javax.swing.JTextField();
        jButton_xacNhan = new javax.swing.JButton();
        jButton_huy = new javax.swing.JButton();
        jButton_kiemTra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã hộ khẩu");

        jLabel2.setText("Mã cuộc họp");

        jLabel7.setText("Chủ hộ");

        jTextField_chuHo.setEditable(false);
        jTextField_chuHo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_chuHoActionPerformed(evt);
            }
        });

        jButton_xacNhan.setText("Ghi nhân tham gia");
        jButton_xacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_xacNhanActionPerformed(evt);
            }
        });

        jButton_huy.setText("Huỷ");
        jButton_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_huyActionPerformed(evt);
            }
        });

        jButton_kiemTra.setText("Kiểm tra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_maCuocHop)
                    .addComponent(jTextField_chuHo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_maHoKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_kiemTra)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_xacNhan)
                .addGap(18, 18, 18)
                .addComponent(jButton_huy)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_maCuocHop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_maHoKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_kiemTra))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_chuHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_xacNhan)
                    .addComponent(jButton_huy))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_chuHoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_chuHoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_chuHoActionPerformed

    private void jButton_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_huyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_huyActionPerformed

    private void jButton_xacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_xacNhanActionPerformed
        // TODO add your handling code here:
        this.quanLySinhHoat.hienthi();
    }//GEN-LAST:event_jButton_xacNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GhiNhanThamGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GhiNhanThamGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GhiNhanThamGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GhiNhanThamGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GhiNhanThamGia().setVisible(true);
            }
        });
    }
    public QuanLySinhHoat quanLySinhHoat;
    private GhiNhanThamGiaController ghiNhanThamGiaController;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_huy;
    private javax.swing.JButton jButton_kiemTra;
    private javax.swing.JButton jButton_xacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField_chuHo;
    private javax.swing.JTextField jTextField_maCuocHop;
    private javax.swing.JTextField jTextField_maHoKhau;
    // End of variables declaration//GEN-END:variables

    public JTextField getjTextField_chuHo() {
        return jTextField_chuHo;
    }
    
    public void setjTextField_chuHo(JTextField jTextField_chuHo) {
        this.jTextField_chuHo = jTextField_chuHo;
    }
    
    public JTextField getjTextField_maHoKhau() {
        return jTextField_maHoKhau;
    }
    
    public void setjTextField_maHoKhau(JTextField jTextField_maHoKhau) {
        this.jTextField_maHoKhau = jTextField_maHoKhau;
    }
    
    public JTextField getjTextField_soNha() {
        return jTextField_maCuocHop;
    }
    
    public void setjTextField_soNha(JTextField jTextField_soNha) {
        this.jTextField_maCuocHop = jTextField_soNha;
    }
    
    public JTextField getjTextField_maCuocHop() {
        return jTextField_maCuocHop;
    }
    
    public void setjTextField_maCuocHop(JTextField jTextField_maCuocHop) {
        this.jTextField_maCuocHop = jTextField_maCuocHop;
    }
    
}
