/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.sinhhoat;

import controller.QuanLySinhHoat.ThongTinCuocHopController;
import java.awt.event.ActionListener;
import javax.swing.JTextField;
import model.CuocHop;
import view.QuanLySinhHoat;

/**
 *
 * @author nnminh322
 */
public class ThongTinCuocHop extends javax.swing.JFrame {

    /**
     * Creates new form GiayMoi
     */
    public ThongTinCuocHop() {
        initComponents();
    }

    public ThongTinCuocHop(QuanLySinhHoat quanLySinhHoat) {
        this.quanLySinhHoat = quanLySinhHoat;
        initComponents();
        this.thongTinCuocHopController = new ThongTinCuocHopController(this);
        ActionListener action = new ThongTinCuocHopController(this);
        this.jButton_xacNhan.addActionListener(action);
    }

    public ThongTinCuocHop(QuanLySinhHoat quanLySinhHoat, CuocHop cuocHop) {
        this.quanLySinhHoat = quanLySinhHoat;
        initComponents();
        this.thongTinCuocHopController = new ThongTinCuocHopController(this);
        ActionListener action = new ThongTinCuocHopController(this);
        this.jButton_xacNhan.addActionListener(action);
        this.jTextField_maCuocHop.setText(cuocHop.getMaCuocHop());
        this.jTextField_chuDe.setText(cuocHop.getChuDe());
        this.jTextField_thoiGian.setText(cuocHop.getThoiGian());
        this.jTextField_diaDiem.setText(cuocHop.getDiaDiem());
        this.jTextField_maCuocHop.setEditable(false);
    }

    /**
     * ThongTinCuocHopController * This method is called from within the
     * constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_maCuocHop = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_chuDe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_diaDiem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_thoiGian = new javax.swing.JTextField();
        jButton_xacNhan = new javax.swing.JButton();
        jButton_huy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã cuộc họp");

        jLabel2.setText("Chủ đề");

        jLabel3.setText("Địa điểm");

        jLabel4.setText("Thời gian");

        jButton_xacNhan.setText("Xác nhận");
        jButton_xacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_xacNhanActionPerformed(evt);
            }
        });

        jButton_huy.setText("Huỷ");
        jButton_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_huyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_maCuocHop, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(52, 52, 52)
                        .addComponent(jTextField_chuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_diaDiem)
                            .addComponent(jTextField_thoiGian))))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_xacNhan)
                .addGap(39, 39, 39)
                .addComponent(jButton_huy)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_maCuocHop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_chuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_diaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_thoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_xacNhan)
                    .addComponent(jButton_huy))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_xacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_xacNhanActionPerformed
        // TODO add your handling code here:
        this.quanLySinhHoat.hienthi();
    }//GEN-LAST:event_jButton_xacNhanActionPerformed

    private void jButton_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_huyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_huyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinCuocHop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinCuocHop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinCuocHop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinCuocHop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongTinCuocHop().setVisible(true);
            }
        });
    }
    public QuanLySinhHoat quanLySinhHoat;
    private ThongTinCuocHopController thongTinCuocHopController;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_huy;
    private javax.swing.JButton jButton_xacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField_chuDe;
    private javax.swing.JTextField jTextField_diaDiem;
    private javax.swing.JTextField jTextField_maCuocHop;
    private javax.swing.JTextField jTextField_thoiGian;
    // End of variables declaration//GEN-END:variables

    public JTextField getjTextField_chuDe() {
        return jTextField_chuDe;
    }

    public void setjTextField_chuDe(JTextField jTextField_chuDe) {
        this.jTextField_chuDe = jTextField_chuDe;
    }

    public JTextField getjTextField_diaDiem() {
        return jTextField_diaDiem;
    }

    public void setjTextField_diaDiem(JTextField jTextField_diaDiem) {
        this.jTextField_diaDiem = jTextField_diaDiem;
    }

    public JTextField getjTextField_maCuocHop() {
        return jTextField_maCuocHop;
    }

    public void setjTextField_maCuocHop(JTextField jTextField_maCuocHop) {
        this.jTextField_maCuocHop = jTextField_maCuocHop;
    }

    public JTextField getjTextField_thoiGian() {
        return jTextField_thoiGian;
    }

    public void setjTextField_thoiGian(JTextField jTextField_thoiGian) {
        this.jTextField_thoiGian = jTextField_thoiGian;
    }

}
